"""initial migration

Revision ID: db3e4e67f730
Revises: 
Create Date: 2026-06-28 17:25:25.950368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3e4e67f730'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dominio', sa.String(), nullable=False),
    sa.Column('fecha_descubrimiento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fuente', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dominio')
    )
    op.create_table('searches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('idioma', sa.String(), nullable=False),
    sa.Column('pais', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('dominio_id', sa.Integer(), nullable=False),
    sa.Column('industria', sa.String(), nullable=True),
    sa.Column('idioma', sa.String(), nullable=True),
    sa.Column('pais', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dominio_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads')
    op.drop_table('companies')
    op.drop_table('searches')
    op.drop_table('domains')
    # ### end Alembic commands ###
